source "http://rubygems.org"

gem 'rails', '2.3.5'
gem 'json'
gem 'haml'
gem 'rspec-rails', '1.3.4'
gem 'will_paginate','>= 2.3.1'
gem 'chronic', '0.2.3'
gem 'packet', '0.1.5'
gem 'progressbar'
gem 'pubmed_search'
gem 'daemons'
gem 'nokogiri'
gem 'bunny', '0.6.0'
gem 'eventmachine'
gem 'redis','0.1.2'
gem 'treetop'
gem 'bio'
gem 'mysql'
gem 'memcache-client'
gem 'ruby-debug', :group => [:development, :test]
