module BlastQueriesHelper
  

  
  @@nuc_fields = {:alignment_view => 'Pairwise',
    :alignments => '100',
    :blast_programs => 'megaBlast',
    :client => 'web',
    :cmd => 'request',
    :composition_based_statistics => '0',
    :database => 'nr',
    :db => 'nucleotide',
    :dbtype => 'gc',
    :default_prog => 'megaBlast',
    :descriptions => '100',
    :expect => '10',
    :filter => 'L',
    :format_object => 'Alignment',
    :format_type => 'HTML',
    :gapcosts => '0 0',
    :genetic_code => '1',
    :get_sequence => 'true',
    :job_title => 'gi|41406056|ref|NM_201414.1| Homo sapiens...',
    :mask_char => '2',
    :mask_color => '1',
    :match_scores => '1,-2',
    :matrix_name => 'PAM30',
    :max_num_seq => '100',
    :megablast => 'on',
    :ncbi_gi => 'false',
    :new_view => 'true',
    :num_diffs => '2',
    :num_opts_diffs => '1',
    :num_overview => '100',
    :old_blast => 'false',
    :page => 'MegaBlast',
    :page_type => 'BlastSearch',
    :program => 'blastn',
    :query => '>gi|41406056|ref|NM_201414.1| Homo sapiens amyloid beta (A4) precursor protein (peptidase nexin-II, Alzheimer disease) (APP), transcript variant 3, mRNAGCTGACTCGCCTGGCTCTGAGCCCCGCCGCCGCGCTCGGGCTCCGTCAGTTTCCTCGGCAGCGGTAGGCGAGAGCACGCGGAGGAGCGTGCGCGGGGGCCCCGGGAGACGGCGGCGGTGGCGGCGCGGGCAGAGCAAGGACGCGGCGGATCCCACTCGCACAGCAGCGCACTCGGTGCCCCGCGCAGGGTCGCGATGCTGCCCGGTTTGGCACTGCTCCTGCTGGCCGCCTGGACGGCTCGGGCGCTGGAGGTACCCACTGATGGTAATGCTGGCCTGCTGGCTGAACCCCAGATTGCCATGTTCTGTGGCAGACTGAACATGCACATGAATGTCCAGAATGGGAAGTGGGATTCAGATCCATCAGGGACCAAAACCTGCATTGATACCAAGGAAGGCATCCTGCAGTATTGCCAAGAAGTCTACCCTGAACTGCAGATCACCAATGTGGTAGAAGCCAACCAACCAGTGACCATCCAGAACTGGTGCAAGCGGGGCCGCAAGCAGTGCAAGACCCATCCCCACTTTGTGATTCCCTACCGCTGCTTAGTTGGTGAGTTTGTAAGTGATGCCCTTCTCGTTCCTGACAAGTGCAAATTCTTACACCAGGAGAGGATGGATGTTTGCGAAACTCATCTTCACTGGCACACCGTCGCCAAAGAGACATGCAGTGAGAAGAGTACCAACTTGCATGACTACGGCATGTTGCTGCCCTGCGGAATTGACAAGTTCCGAGGGGTAGAGTTTGTGTGTTGCCCACTGGCTGAAGAAAGTGACAATGTGGATTCTGCTGATGCGGAGGAGGATGACTCGGATGTCTGGTGGGGCGGAGCAGACACAGACTATGCAGATGGGAGTGAAGACAAAGTAGTAGAAGTAGCAGAGGAGGAAGAAGTGGCTGAGGTGGAAGAAGAAGAAGCCGATGATGACGAGGACGATGAGGATGGTGATGAGGTAGAGGAAGAGGCTGAGGAACCCTACGAAGAAGCCACAGAGAGAACCACCAGCATTGCCACCACCACCACCACCACCACAGAGTCTGTGGAAGAGGTGGTTCGAGTTCCTACAACAGCAGCCAGTACCCCTGATGCCGTTGACAAGTATCTCGAGACACCTGGGGATGAGAATGAACATGCCCATTTCCAGAAAGCCAAAGAGAGGCTTGAGGCCAAGCACCGAGAGAGAATGTCCCAGGTCATGAGAGAATGGGAAGAGGCAGAACGTCAAGCAAAGAACTTGCCTAAAGCTGATAAGAAGGCAGTTATCCAGCATTTCCAGGAGAAAGTGGAATCTTTGGAACAGGAAGCAGCCAACGAGAGACAGCAGCTGGTGGAGACACACATGGCCAGAGTGGAAGCCATGCTCAATGACCGCCGCCGCCTGGCCCTGGAGAACTACATCACCGCTCTGCAGGCTGTTCCTCCTCGGCCTCGTCACGTGTTCAATATGCTAAAGAAGTATGTCCGCGCAGAACAGAAGGACAGACAGCACACCCTAAAGCATTTCGAGCATGTGCGCATGGTGGATCCCAAGAAAGCCGCTCAGATCCGGTCCCAGGTTATGACACACCTCCGTGTGATTTATGAGCGCATGAATCAGTCTCTCTCCCTGCTCTACAACGTGCCTGCAGTGGCCGAGGAGATTCAGGATGAAGTTGATGAGCTGCTTCAGAAAGAGCAAAACTATTCAGATGACGTCTTGGCCAACATGATTAGTGAACCAAGGATCAGTTACGGAAACGATGCTCTCATGCCATCTTTGACCGAAACGAAAACCACCGTGGAGCTCCTTCCCGTGAATGGAGAGTTCAGCCTGGACGATCTCCAGCCGTGGCATTCTTTTGGGGCTGACTCTGTGCCAGCCAACACAGAAAACGAAGTTGAGCCTGTTGATGCCCGCCCTGCTGCCGACCGAGGACTGACCACTCGACCAGGTTCTGGGTTGACAAATATCAAGACGGAGGAGATCTCTGAAGTGAAGATGGATGCAGAATTCCGACATGACTCAGGATATGAAGTTCATCATCAAAAATTGGTGTTCTTTGCAGAAGATGTGGGTTCAAACAAAGGTGCAATCATTGGACTCATGGTGGGCGGTGTTGTCATAGCGACAGTGATCGTCATCACCTTGGTGATGCTGAAGAAGAAACAGTACACATCCATTCATCATGGTGTGGTGGAGGTTGACGCCGCTGTCACCCCAGAGGAGCGCCACCTGTCCAAGATGCAGCAGAACGGCTACGAAAATCCAACCTACAAGTTCTTTGAGCAGATGCAGAACTAGACCCCCGCCACAGCAGCCTCTGAAGTTGGACAGCAAAACCATTGCTTCACTACCCATCGGTGTCCATTTATAGAATAATGTGGGAAGAAACAAACCCGTTTTATGATTTACTCATTATCGCCTTTTGACAGCTGTGCTGTAACACAAGTAGATGCCTGAACTTGAATTAATCCACACATCAGTAATGTATTCTATCTCTCTTTACATTTTGGTCTCTATACTACATTATTAATGGGTTTTGTGTACTGTAAAGAATTTAGCTGTATCAAACTAGTGCATGAATAGATTCTCTCCTGATTATTTATCACATAGCCCCTTAGCCAGTTGTATATTATTCTTGTGGTTTGTGACCCAATTAAGTCCTACTTTACATATGCTTTAAGAATCGATGGGGGATGCTTCATGTGAACGTGGGAGTTCAGCTGCTTCTCTTGCCTAAGTATTCCTTTCCTGATCACTATGCATTTTAAAGTTAAACATTTTTAAGTATTTCAGATGCTTTAGAGAGATTTTTTTTCCATGACTGCATTTTACTGTACAGATTGCTGCTTCTGCTATATTTGTGATATAGGAATTAAGAGGATACACACGTTTGTTTCTTCGTGCCTGTTTTATGTGCACACATTAGGCATTGAGACTTCAAGCTTTTCTTTTTTTGTCCACGTATCTTTGGGTCTTTGATAAAGAAAAGAATCCCTGTTCATTGTAAGCACTTTTACGGGGCGGGTGGGGAGGGGTGCTCTGCTGGTCTTCAATTACCAAGAATTCTCCAAAACAATTTTCTGCAGGATGATTGTACAGAATCATTGCTTATGACATGATCGCTTTCTACACTGTATTACATAAATAAATTAAATAAAATAACCCCGGGCAAGACTTTTCTTTGAAGGATGACTACAGACATTAAATAATCGAAGTAATTTTGGGTGGGGAGAAGAGGCAGATTCAATTTTCTTTAACCAGTCTGAAGTTTCATTTATGATACAAAAGAAGATGAAAATGGAAGTGGCAATATAAGGGGATGAGGAAGGCATGCCTGGACAAACCCTTCTTTTAAGATGTGTCTTCAATTTGTATAAAATGGTGTTTTCATGTAAATAAATACATTCTTGGAGGAGCAAAAAAAAAAAAAAA',
    :repeats => 'repeat_9606',
    :saved_search => 'true',
    :selected_prog_type => 'megaBlast',
    :service => 'plain',
    :short_query_adjust => 'on',
    :show_cds_feature => 'false',
    :show_linkout => 'true',
    :show_overview => 'true',
    :stype => 'nucleotide',
    :template_length => '0',
    :template_type => '0',
    :uniq_defaults_name => 'A_SearchDefaults_1LCdlg_8AY_1Z57DM3ot_GTSlj_1Ak2AN',
    :user_default_match_scores => '0',
    :user_default_prog_type => 'megaBlast',
    :word_size => '28'
  }
  @@protein_fields = {:alignment_view => 'Pairwise',
    :alignments => '100',
    :blast_programs => 'tblastn',
    :client => 'web',
    :cmd => 'request',
    :composition_based_statistics => '2',
    :database => 'nr',
    :db => 'protein',
    :descriptions => '100',
    :expect => '10',
    :format_object => 'Alignment',
    :format_type => 'HTML',
    :gapcosts => '11 1',
    :genetic_code => '1',
    :get_sequence => 'on',
    :job_title => 'gi|112927|sp|P05067.3|A4_HUMAN RecName: Full=Amyloid...',
    :mask_char => '2',
    :mask_color => '1',
    :match_scores => '1,-2',
    :matrix_name => 'BLOSUM62',
    :max_num_seq => '100',
    :num_diffs => '0',
    :num_opts_diffs => '0',
    :num_overview => '100',
    :old_blast => 'false',
    :page => 'Translations',
    :page_type => 'BlastSearch',
    :program => 'tblastn',
    :query => '>gi|112927|sp|P05067.3|A4_HUMAN RecName: Full=Amyloid beta A4 protein;MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAMSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN',
    :query_index => '0',
    :repeats => 'repeat_9606',
    :selected_prog_type => 'tblastn',
    :service => 'plain',
    :short_query_adjust => 'on',
    :show_linkout => 'on',
    :show_overview => 'on',
    :stype => 'nucleotide',
    :template_length => '0',
    :template_type => '0',
    :ungapped_alignment => 'no',
    :user_default_prog_type => 'tblastn',
    :word_size => '3'
  }
  
  def blast_form(sequence)
    fields = sequence.amino_acid? ? @@protein_fields : @@nuc_fields
    fields[:query] = sequence.fasta_data
    fields[:job_title] = awesome_truncate(sequence.fasta_data, 40)
    
    # I couldn't figure out how to make form_tag work here. I'm not sure why. Probably because I'm stupid.
    returning '<form action="http://blast.ncbi.nlm.nih.gov/Blast.cgi" method="post" target="_blank"><fieldset>' do |html|
      fields.each{|k,v| html << hidden_field_tag(k.to_s.upcase, v) }
      html << submit_tag("Blast this Sequence")
      html << '</fieldset></form>'
    end
  end
  
  
end
